language: ruby
sudo: false
before_install:
  - gem install bundler:1.17.3
cache: bundler

rvm:
  - 2.2.4
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
